### ISSUE TITLE
Images don't load in my graph

### ISSUE THREAD

**Issue by Zeidiez** [phonetonote/generate-images#1]
Hi, I use this tool on a daily basis, but since yesterday all the images generated by the AI displayed through the Roam Extension are not loading on my graph. 

I think is not a problem with the generation of the image or the link hosting (the photos are indeed hosted in the link) but for some reason, it doesn't load in the graph. Here are some pictures...

How does it look in my graph:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/119615420/205108202-477367ed-d7d2-4088-a66e-26323f8fed54.png">
<img width="893" alt="image" src="https://user-images.githubusercontent.com/119615420/205108437-d12ea172-6557-4748-b1d0-6e2cad724560.png">

How does it look in the host link:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/119615420/205108728-1afacd8f-c25e-4707-87e6-57930af0f597.png">

Is there something of the Extension or my Graph? Can I solve it myself?

**Comment by scottrblock** [comment]
Hey @Zeidiez this was a temporary issue because I had inadvertently turned on a setting to throttle hot linking on the URLs. This should be resolved now!
